#pragma once

// =============================================================================
// DEVICE SECRETS — TEMPLATE
//
// How to use:
//   1. Copy this file next to itself as  secrets.h
//        cp firmware/include/secrets_template.h firmware/include/secrets.h
//   2. Replace every placeholder below with the values for YOUR building.
//   3. Never commit secrets.h: it is listed in .gitignore, and the CI secret
//      scanner (gitleaks) fails the build if a credential slips into git.
//
// Why so few secrets on the device: the ESP32 only needs to reach the
// building gateway's private MQTT broker. E-mail alerts, users and reports
// all live on the gateway, so a stolen controller exposes nothing beyond its
// own MQTT login, which can be revoked on the broker in seconds.
// =============================================================================

// ── Wi-Fi ─────────────────────────────────────────────────────────────────────
// The network the controller joins. Use a dedicated IoT network / VLAN when
// the building has one, so the controller can only talk to the gateway.
#define WIFI_SSID       "your-building-iot-network"
#define WIFI_PASSWORD   "change-me"

// ── MQTT broker (the Hestia gateway) ─────────────────────────────────────────
// Host name or IP of the gateway running deploy/docker-compose.yml.
// Port 8883 = MQTT over TLS. Plain 1883 is disabled on the gateway.
#define MQTT_HOST       "hestia-gateway.local"
#define MQTT_PORT       8883

// Per-device login created on the gateway with
//   deploy/mosquitto/add-device.sh <device-id>
// The broker's ACL only lets this user publish its own telemetry and read
// its own command topic.
#define MQTT_USERNAME   "esp32_1"
#define MQTT_PASSWORD   "change-me"

// Certificate of the authority that signed the gateway's TLS certificate
// (deploy/mosquitto/certs/ca.crt, generated by deploy/mosquitto/make-certs.sh).
// Paste the whole PEM block, keeping the BEGIN/END lines.
#define MQTT_CA_CERT \
    "-----BEGIN CERTIFICATE-----\n" \
    "paste-the-gateway-ca-certificate-here\n" \
    "-----END CERTIFICATE-----\n"

// ── Command signing key ──────────────────────────────────────────────────────
// Shared secret used to verify that a command really comes from the gateway
// (HMAC-SHA256 over the command, a sequence number and a timestamp). Must be
// identical to HESTIA_DEVICE_COMMAND_KEY in the gateway's .env file.
// Generate one with:  python -c "import secrets; print(secrets.token_hex(32))"
#define COMMAND_HMAC_KEY "replace-with-64-hex-characters-generated-as-above"
