// The safety report: what an inspector, an insurer or a new owner asks for.
// It is generated by the gateway (GET /api/report), which also journals that
// it was produced and with which chain head, so a printed copy can later be
// matched against the journal. Print it, or "save as PDF" from the browser.
import { useState } from "react";
import { Link } from "react-router";
import { ArrowLeftIcon, PrinterIcon } from "@phosphor-icons/react";
import { useI18n, type Key } from "../lib/i18n";
import { useApi } from "../lib/useApi";
import type { CheckStatus, JournalEntry, Trust } from "../lib/types";
import { Card, LevelPill, formatDate } from "../components/ui";

interface Report {
  title: string;
  site_name: string;
  mode: "twin" | "device";
  generated_at: string;
  generated_by: string;
  period: { from: string; to: string; days: number };
  integrity: { ok: boolean; entries_checked: number; head_hash: string; first_broken_id: number | null; problem: string };
  summary: Record<"alarms" | "alarm_resets" | "over_temperatures" | "sensor_trust_changes" | "outages" | "maintenance_records", number>;
  findings: string[];
  incidents: JournalEntry[];
  changes: JournalEntry[];
  maintenance: {
    status: CheckStatus[];
    records: { id: number; kind: string; sensor: string; performed_at: string; technician: string; result: string; notes: string }[];
  };
  current_state: Trust | null;
}

const PERIODS = [7, 30, 90, 365];
const SENSOR_KEY: Record<string, Key> = {
  h2: "safety.sensor.h2",
  temperature: "safety.sensor.temperature",
  electrolyte: "safety.sensor.electrolyte",
  installation: "safety.sensor.installation",
};

export function ReportPage() {
  const { t, lang, fmt } = useI18n();
  const [days, setDays] = useState(30);
  const { data: r, error } = useApi<Report>(`/api/report?days=${days}`);

  return (
    <div className="stack report">
      <div className="row spread no-print">
        <Link to="/safety" className="btn ghost">
          <ArrowLeftIcon size={16} /> {t("nav.safety")}
        </Link>
        <div className="row">
          <div className="segmented" role="group" aria-label={t("report.period")}>
            {PERIODS.map((d) => (
              <button key={d} aria-pressed={days === d} onClick={() => setDays(d)}>
                {d} {t("report.days")}
              </button>
            ))}
          </div>
          <button className="btn primary" onClick={() => window.print()} disabled={!r}>
            <PrinterIcon size={16} /> {t("report.print")}
          </button>
        </div>
      </div>

      {error && <div className="error">{error}</div>}
      {!r && !error && <p className="dim">{t("common.loading")}</p>}
      {r && (
        <>
          <header className="card">
            <h1 style={{ marginBottom: 4 }}>{t("report.title")}</h1>
            <div className="dim">
              {r.site_name} · {formatDate(r.period.from, lang, false)} → {formatDate(r.period.to, lang, false)}
            </div>
            <div className="faint">
              {t("report.generated")} {formatDate(r.generated_at, lang)} · {r.generated_by}
            </div>
          </header>

          <Card title={t("report.integrity")}>
            <div className="row">
              <span className={`pill ${r.integrity.ok ? "ok" : "danger"}`}>{r.integrity.ok ? t("safety.verified") : t("safety.tampered")}</span>
              <span>
                {fmt(r.integrity.entries_checked)} {t("safety.verify.checked")}
              </span>
            </div>
            <p className="hint">{t("report.integrity.how")}</p>
            <div className="hash">{r.integrity.head_hash}</div>
          </Card>

          <Card title={t("report.findings")}>
            {r.findings.length === 0 ? (
              <p>{t("report.none")}</p>
            ) : (
              <ul className="findings">
                {r.findings.map((f) => (
                  <li key={f} className="degraded">
                    {f}
                  </li>
                ))}
              </ul>
            )}
          </Card>

          <div className="grid grid-3">
            {(Object.keys(r.summary) as (keyof Report["summary"])[]).map((k) => (
              <div className="card metric" key={k}>
                <span className="label">{t(`report.summary.${k}`)}</span>
                <span className="value">{fmt(r.summary[k])}</span>
              </div>
            ))}
          </div>

          {r.current_state && (
            <Card title={t("report.current")}>
              <div className="row">
                {(["h2", "temperature", "electrolyte", "link"] as const).map((s) => (
                  <span key={s} className="row" style={{ gap: 6 }}>
                    {t(`safety.sensor.${s}`)} <LevelPill level={r.current_state?.sensors[s].level ?? "untrusted"} />
                  </span>
                ))}
              </div>
            </Card>
          )}

          <Card title={t("safety.maintenance")}>
            <table>
              <thead>
                <tr>
                  <th>{t("safety.check")}</th>
                  <th>{t("safety.state")}</th>
                  <th>{t("safety.last")}</th>
                  <th>{t("safety.next_due")}</th>
                </tr>
              </thead>
              <tbody>
                {r.maintenance.status.map((c) => (
                  <tr key={`${c.kind}:${c.sensor}`}>
                    <td>
                      {t(`safety.kind.${c.kind}`)} · {t(SENSOR_KEY[c.sensor] ?? "safety.sensor.installation")}
                    </td>
                    <td>{t(`safety.state.${c.state}`)}</td>
                    <td>{formatDate(c.last_at, lang, false)}</td>
                    <td>{formatDate(c.next_due, lang, false)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            <h3 style={{ marginTop: 18 }}>{t("report.records")}</h3>
            <EntryTable
              rows={r.maintenance.records.map((m) => ({
                key: m.id,
                when: m.performed_at,
                what: `${m.kind.replace("_", " ")} · ${m.sensor} · ${m.result.toUpperCase()}${m.notes ? ` · ${m.notes}` : ""}`,
                who: m.technician,
              }))}
            />
          </Card>

          <Card title={t("report.incidents")}>
            <EntryTable rows={r.incidents.map((e) => ({ key: e.id, when: e.ts, what: e.summary, who: e.actor }))} />
          </Card>

          <Card title={t("report.changes")}>
            <EntryTable rows={r.changes.map((e) => ({ key: e.id, when: e.ts, what: e.summary, who: e.actor }))} />
          </Card>

          <p className="faint">{t("report.footer")}</p>
        </>
      )}
    </div>
  );
}

function EntryTable({ rows }: { rows: { key: number; when: string; what: string; who: string }[] }) {
  const { t, lang } = useI18n();
  if (rows.length === 0) return <p className="dim">{t("report.none_period")}</p>;
  return (
    <table>
      <thead>
        <tr>
          <th style={{ width: 170 }}>{t("report.when")}</th>
          <th>{t("report.what")}</th>
          <th style={{ width: 120 }}>{t("report.who")}</th>
        </tr>
      </thead>
      <tbody>
        {rows.map((row) => (
          <tr key={row.key}>
            <td className="num">{formatDate(row.when, lang)}</td>
            <td>{row.what}</td>
            <td>{row.who}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}
