// Realistic snapshots for component tests.
//   snapshot(): the live bench at mid-morning, producing, cooling loop off.
//   siteSnapshot(): a simulated building at a summer noon, producing and cooling.
import type { Snapshot, Telemetry } from "./lib/types";

const telemetry: Telemetry = {
  device_id: "twin_1",
  seq: 42,
  ts: "2025-07-10T09:00:00+00:00",
  uptime_s: 3600,
  firmware: "twin-2.1.0",
  electrolyte_c: 52.4,
  koh_wt_pct: 30.1,
  level_low: false,
  h2_ppm: 56,
  tank_bar: 0,
  temp_valid: true,
  koh_valid: true,
  h2_valid: true,
  tank_valid: true,
  mode: "AUTO",
  phase: "ELECTROLYSIS",
  reason: "Producing H₂",
  electrolyser: true,
  cooling_pump: false,
  koh_dosing: false,
  water_makeup: false,
  ventilation: false,
  h2_relay_closed: true,
  h2_warning: false,
  h2_alarm_latched: false,
  production_permit: true,
  koh_low_pct: 25,
  koh_high_pct: 32,
  temp_alert_c: 70,
  h2_warning_ppm: 500,
  h2_alarm_ppm: 2000,
  storage_mawp_bar: 0,
};

export function snapshot(overrides: Partial<Snapshot> = {}): Snapshot {
  return {
    version: "2.1.0",
    mode: "twin",
    site_name: "Test site",
    updated_at: "2025-07-10T09:00:00+00:00",
    online: true,
    telemetry,
    site: {
      source: "twin",
      timestamp: "2025-07-10T09:00:00+00:00",
      local_time: "2025-07-10 10:00",
      outdoor_c: 29,
      humidity_pct: 40,
      irradiance_wpm2: 700,
      pv_w: 0,
      electrolyser_w: 1000,
      available_w: 1000,
      load_w: null,
      heat_pump_w: null,
      fuel_cell_w: null,
      battery_w: null,
      battery_soc_pct: null,
      grid_w: null,
      curtailed_w: null,
      h2_tank_kg: null,
      h2_tank_pct: null,
      tank_bar: null,
      tank_mawp_bar: null,
      h2_vented_kg: null,
      indoor_c: null,
      hvac_mode: null,
      hvac_w: null,
      fuel_cell_heat_w: null,
      boiler_w: null,
      end_use: null,
      room_h2_ppm: 0,
    },
    trust: {
      overall: "ok",
      h2_trusted: true,
      h2_why: "H₂ detector trusted",
      sensors: {
        link: { name: "link", level: "ok", score: 100, value: null, findings: [], received: 100, gaps: 0, reboots: 0 },
        h2: { name: "h2", level: "ok", score: 100, value: 56, findings: [], baseline_ppm: 55 },
        temperature: { name: "temperature", level: "ok", score: 100, value: 52.4, findings: [] },
        electrolyte: { name: "electrolyte", level: "ok", score: 100, value: 30.1, findings: [] },
      },
    },
    energy: {
      permit: true,
      permit_reason: "Producing on surplus power",
      hvac: { mode: "off", setpoint_c: 0, allow_h2: false, emergency: false, reason: "No building on this installation" },
    },
    advice: {
      available: true,
      pv_forecast_w: 1500,
      heat_demand_forecast_w: 0,
      production_level: 4,
      production_label: "FULL",
      anomaly: false,
      anomaly_severity: 0,
    },
    twin: {
      model: "bench",
      speed: 60,
      paused: false,
      faults: [],
      available_faults: ["leak_small", "leak_large", "cooling_failure", "fan_failure"],
      sim_time: "2025-07-10T09:00:00+00:00",
      local_time: "2025-07-10 10:00",
      totals: { h2_produced_kg: 0.02 },
      electrolyte_l: 20,
      electrolyte_wt_pct: 30.1,
      conductivity_s_per_cm: 0.95,
      stack: {
        rated_w: 1000,
        min_w: 200,
        cells: 12,
        cell_voltage: 1.99,
        current_a: 40.1,
        faraday_efficiency: 0.978,
        heat_w: 250,
        kwh_per_kg: 59.6,
        h2_g_per_h: 16.8,
      },
    },
    journal_head: "abcdef0123456789",
    sim: null,
    ...overrides,
  };
}

export function siteSnapshot(overrides: Partial<Snapshot> = {}): Snapshot {
  const base = snapshot();
  return {
    ...base,
    site_name: "Simulator, Tunis",
    telemetry: { ...telemetry, tank_bar: 17.9, storage_mawp_bar: 30 },
    site: {
      ...(base.site as NonNullable<Snapshot["site"]>),
      source: "simulation",
      pv_w: 4120,
      electrolyser_w: 1840,
      available_w: 1880,
      load_w: 540,
      heat_pump_w: 690,
      fuel_cell_w: 0,
      battery_w: 0,
      battery_soc_pct: 100,
      grid_w: -1050,
      curtailed_w: 0,
      h2_tank_kg: 2.31,
      h2_tank_pct: 58,
      tank_bar: 17.9,
      tank_mawp_bar: 30,
      h2_vented_kg: 0,
      indoor_c: 25.8,
      hvac_mode: "cool",
      hvac_w: -2070,
      fuel_cell_heat_w: 0,
      boiler_w: 0,
      end_use: "fuel_cell",
    },
    ...overrides,
  };
}
